name: Java CI
on: [push]
jobs:
  MavenBuild:
     runs-on: ubuntu-latest
     steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        
      
            
      - name: Code validate
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      -  run: 
            mvn validate
            
      - name: Code compile
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      -  run: 
            mvn compile
            
      - name: Code Test
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      -  run:  
            mvn test

      
      - name: Build with Maven
         #run the Maven package target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
         #Forces a check for updated releases and snapshots on remote repositories
        run: mvn --batch-mode --update-snapshots package
      
        
      - name: Code verify
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      -  run:  
            mvn verify
            
      - name: Code install
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      -  run: 
            mvn clean install

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=java-maven-demo -Dsonar.projectName='java-maven-demo'
